import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
public class restaurantwindow extends javax.swing.JFrame {

  int ChickenNumber,meatNumber,waterNumbrt,juiceNumber;
    double chickenPrice,meatPrice,waterPrice,juicePrice;
    final double chicken_cost=30.0,meat_cost=30.0,water_cost=3.0,juice_cost=5;
    double subTotal,Total,vat;
    int customer_counter;
    PrintWriter Output;
    //PrintWriter output= new PrintWriter(System.out);
     

    public restaurantwindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Chicken_counter = new javax.swing.JSpinner();
        Chicken_cheese = new javax.swing.JCheckBox();
        Chicken_shawarma_price = new javax.swing.JLabel();
        Meat_shawarma_price = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Meat_counter = new javax.swing.JSpinner();
        Meat_cheese = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        water_counter = new javax.swing.JSpinner();
        The_price_of_water = new javax.swing.JLabel();
        The_price_of_the_juice = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        juicecounter = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        totalx = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelTax = new javax.swing.JLabel();
        aa = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        zz = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        calculat = new javax.swing.JButton();
        New_bill = new javax.swing.JButton();
        Save_bill = new javax.swing.JButton();
        customer_counterNumber = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("نظام ادارة المطعم");

        jLabel3.setText("تطوير فريق نادى البرمجه نسخه 1.0");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "المأكولات", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("شاورما دجاج");

        Chicken_counter.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        Chicken_counter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Chicken_counterStateChanged(evt);
            }
        });

        Chicken_cheese.setText("جبنه");
        Chicken_cheese.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Chicken_cheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chicken_cheeseActionPerformed(evt);
            }
        });

        Chicken_shawarma_price.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Chicken_shawarma_price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Chicken_shawarma_price.setText("0.0 جنيه");

        Meat_shawarma_price.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Meat_shawarma_price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Meat_shawarma_price.setText("0.0 جنيه");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("شاورما لحم");

        Meat_counter.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        Meat_counter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Meat_counterStateChanged(evt);
            }
        });

        Meat_cheese.setText("جبنه");
        Meat_cheese.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Meat_cheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Meat_cheeseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Chicken_shawarma_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Meat_shawarma_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Chicken_cheese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Chicken_counter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Meat_cheese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Meat_counter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Chicken_counter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chicken_cheese)
                    .addComponent(Chicken_shawarma_price))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Meat_counter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Meat_cheese)
                    .addComponent(Meat_shawarma_price))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "المشروبات", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ماء");

        water_counter.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        water_counter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                water_counterStateChanged(evt);
            }
        });

        The_price_of_water.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        The_price_of_water.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        The_price_of_water.setText("0.0 جنيه");

        The_price_of_the_juice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        The_price_of_the_juice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        The_price_of_the_juice.setText("0.0 جنيه");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("عصير");

        juicecounter.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        juicecounter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                juicecounterStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(The_price_of_the_juice, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(juicecounter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(The_price_of_water, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(water_counter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(water_counter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(The_price_of_water)
                    .addComponent(jLabel11)
                    .addComponent(juicecounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(The_price_of_the_juice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الحساب", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        totalx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalx.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalx.setText("المجموع:");

        labelTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotal.setText("0.0 جنيه");

        labelTax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTax.setText("0.0 جنيه");

        aa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aa.setText("الاجمالى:");

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalLabel.setText("0.0 جنيه");

        zz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        zz.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        zz.setText("الضريبه:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTax, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(totalx, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(zz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalx)
                    .addComponent(labelTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTax)
                    .addComponent(zz, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aa)
                    .addComponent(totalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الحساب", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        calculat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calculat.setText("حساب");
        calculat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatActionPerformed(evt);
            }
        });

        New_bill.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        New_bill.setText("فاتورة جديده");
        New_bill.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        New_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_billActionPerformed(evt);
            }
        });

        Save_bill.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Save_bill.setText("حفظ الفاتوره ");
        Save_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_billActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(calculat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(Save_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(New_bill)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(calculat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Save_bill)
                    .addComponent(New_bill)))
        );

        customer_counterNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customer_counterNumber.setText("رقم الفتوره:0");

        Exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Exit.setText("خروج");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(customer_counterNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Exit)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customer_counterNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Chicken_cheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chicken_cheeseActionPerformed
        // TODO add your handling code here:
        if(Chicken_cheese.isSelected()){
        chickenPrice+=ChickenNumber*5; //chickenPrice=0+3=3
        }else{
        chickenPrice-=ChickenNumber*5;//chickenPrice=0-3=-3
        }
        Chicken_shawarma_price.setText(chickenPrice+"جنيه");
    }//GEN-LAST:event_Chicken_cheeseActionPerformed

    private void Chicken_counterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Chicken_counterStateChanged
        // TODO add your handling code here:
       ChickenNumber= (Integer)Chicken_counter.getValue();
       chickenPrice=chicken_cost * ChickenNumber;
       Chicken_shawarma_price.setText(chickenPrice+"جنيه");
    }//GEN-LAST:event_Chicken_counterStateChanged

    private void Meat_counterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Meat_counterStateChanged
        // TODO add your handling code here:
          meatNumber= (Integer)Meat_counter.getValue();
       meatPrice=meat_cost * meatNumber;
       Meat_shawarma_price.setText(meatPrice+"جنيه");
    }//GEN-LAST:event_Meat_counterStateChanged

    private void water_counterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_water_counterStateChanged
        // TODO add your handling code here:
          waterNumbrt= (Integer)water_counter.getValue();
       waterPrice=water_cost * waterNumbrt;
      The_price_of_water.setText(waterPrice+"جنيه");
    }//GEN-LAST:event_water_counterStateChanged

    private void juicecounterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_juicecounterStateChanged
        // TODO add your handling code here:
         juiceNumber= (Integer)juicecounter.getValue();
       juicePrice=juice_cost * juiceNumber;
      The_price_of_the_juice.setText(juicePrice+"جنيه");
    }//GEN-LAST:event_juicecounterStateChanged

    private void Meat_cheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Meat_cheeseActionPerformed
        // TODO add your handling code here:
         if(Meat_cheese.isSelected()){
        meatPrice+=meatNumber*5;
        }else{
        meatPrice-=meatNumber*5;
        }
        Meat_shawarma_price.setText(meatPrice+"جنيه");
    }//GEN-LAST:event_Meat_cheeseActionPerformed

    private void calculatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatActionPerformed
        // TODO add your handling code here: chickenPrice,meatPrice,waterPrice,juicePrice
        subTotal=ChickenNumber*chickenPrice+meatNumber*meatPrice+waterNumbrt*waterPrice+juiceNumber*juicePrice;
        labelTotal.setText(subTotal+"جنيه");
       
        vat=subTotal*0.05;// ex:-   1.750000000
        vat*=100; //175.0000000
        vat=(double)((int)vat);//175 => 175.0
        vat/=100;//1.75 ☻
        labelTax.setText(vat+"جنيه");
        Total=subTotal+vat;
        totalLabel.setText(Total+"جنيه");
    }//GEN-LAST:event_calculatActionPerformed

    private void Save_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_billActionPerformed
       
        
      try {
        if(Total!=0){
         Output = new PrintWriter("billNo."+customer_counter+".txt");
        Output.println("رقم الفاتوره "+customer_counter);
        Output.println("===========================");
        if(ChickenNumber!=0){
                Output.print(ChickenNumber+" شاورما دجاج ");
              if(Chicken_cheese.isSelected()){
                      Output.println(" بالجبنه");

              }  
             Output.println(chickenPrice+" جنيه");

        }
        
           if(meatNumber!=0){
                Output.print(meatNumber+" شاورما لحم ");
              if(Meat_cheese.isSelected()){
                      Output.println(" بالجبنه");

              }  
             Output.println(meatPrice+" جنيه");

        }
           //waterPrice,juicePrice
                 if(ChickenNumber!=0){
                Output.print(waterNumbrt+" ماء ");
             
             Output.println(waterPrice+" جنيه");

        }
        
           if(meatNumber!=0){
                Output.print(juiceNumber+" عصير ");  
             Output.println(juicePrice+" جنيه");

        }//    double subTotal,Total,vat;
                Output.println("-------------------------"); 
                Output.println(" المجموع: "+subTotal+"جنيه");  
                Output.println(" الضريبه: "+vat+"جنيه");  
                Output.println(" الاجمالى: "+Total+"جنيه");  
                Output.println();  
                Output.println(" ***شكرا لطلبك *** ");  
                Output.close();

        }
      } catch (FileNotFoundException ex) {
          Logger.getLogger(restaurantwindow.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_Save_billActionPerformed

    private void New_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_billActionPerformed
         if(Total!=0){
         Chicken_counter.setValue(0);
         Meat_counter.setValue(0);
         water_counter.setValue(0);
         juicecounter.setValue(0);
         Chicken_cheese.setSelected(false);
         Meat_cheese.setSelected(false);
         labelTotal.setText("0.0جنيه");
         labelTax.setText("0.0جنيه");
         totalLabel.setText("0.0جنيه");
            subTotal=0;
            Total=0;
            vat=0;
            customer_counter++;
            customer_counterNumber.setText(customer_counter+"رقم الفاتوره ");
            
         
         }
    }//GEN-LAST:event_New_billActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new restaurantwindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Chicken_cheese;
    private javax.swing.JSpinner Chicken_counter;
    private javax.swing.JLabel Chicken_shawarma_price;
    private javax.swing.JButton Exit;
    private javax.swing.JCheckBox Meat_cheese;
    private javax.swing.JSpinner Meat_counter;
    private javax.swing.JLabel Meat_shawarma_price;
    private javax.swing.JButton New_bill;
    private javax.swing.JButton Save_bill;
    private javax.swing.JLabel The_price_of_the_juice;
    private javax.swing.JLabel The_price_of_water;
    private javax.swing.JLabel aa;
    private javax.swing.JButton calculat;
    private javax.swing.JLabel customer_counterNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner juicecounter;
    private javax.swing.JLabel labelTax;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalx;
    private javax.swing.JSpinner water_counter;
    private javax.swing.JLabel zz;
    // End of variables declaration//GEN-END:variables


}
